import allStopsData from './allStops.json';

/** One physical platform within a stop group. */
export type CompactPlatform = {
  id: string; // PID stop id used by the departureboards API, e.g. "U321Z101P"
  platform: string; // platform label, e.g. "M1", "A", "1"
  type: string; // platform mainTrafficType, e.g. "metroA" | "tram" | "bus"
  lines: string[]; // line names serving this platform, e.g. ["A"] or ["9", "22"]
};

/** A stop group (one station / stop name) and all its platforms. */
export type CompactStop = {
  id: string; // stable unique key (first platform id within Prague)
  name: string;
  avgLat: number;
  avgLon: number;
  mainTrafficType: string; // "metroA" | "metroAB" | "tram" | "bus" | ...
  stops: CompactPlatform[];
};

/** Every Prague (district "AB") stop group, sorted by name. Generated by scripts/process-stops.ts. */
export const allStops = allStopsData as unknown as CompactStop[];

export const isMetroType = (type: string): boolean => type.startsWith('metro');
